version: '2'
services:
  bot:
    build: .
    cpu_shares: 73
    networks:
      - db_name_net
    volumes:
      - /home/deploy/projectName/src/config.toml:/config.toml
      - /home/deploy/projectName/image:/image
    ports:
      - "3091:3091"
    logging:
      driver: gelf
      options:
        gelf-address: "udp://85.143.214.161:12201"
        tag: docker.app.db_name
    depends_on:
      - postgres

  postgres:
    image: postgres:12
    networks:
      - db_name_net
    volumes:
      - /home/deploy/projectName/postgres/volume:/var/lib/postgresql/data
      - /home/deploy/projectName/postgres/logs:/logs
    ports:
      - "5646:5432"
    environment:
      POSTGRES_PASSWORD: ktulhu77

networks:
  db_name_net:
    driver: bridge