version: '2'
services:
  app:
    build: .
    networks:
      - db_name_net
    depends_on:
      - postgres

  postgres:
    image: postgres:12
    volumes:
      - postgres_data_CompanyName_12:/var/lib/postgresql/data
    ports:
      - "5438:5432"
    environment:
      POSTGRES_PASSWORD: ktulhu77

volumes:
  postgres_data_CompanyName_12:

networks:
  db_name_net:
    driver: bridge
